/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.repository;

import com.nmac.payments.entities.NmacPymntAcnts ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for NmacPymntAcnts
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface NmacPymntAcntsRepository extends PagingAndSortingRepository<NmacPymntAcnts, Integer> {
/*
		NmacPymntAcnts findBySfid(String sfid);
*/

}