/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nmac.payments.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "nmac_usr_prfl"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="nmac_usr_prfl", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="NmacUsrPrfl.countAll", query="SELECT COUNT(x) FROM NmacUsrPrfl x" )
} )
public class NmacUsrPrfl implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="usr_ky")
    private Integer    usrKy        ;


    @Column(name="usr_id", length=40)
    private String     usrId        ;


    @Column(name="usr_frst_nm", length=255)
    private String     usrFrstNm    ;


    @Column(name="usr_lst_nm", length=255)
    private String     usrLstNm     ;


    @Column(name="flex_clmn1_tx", length=255)
    private String     flexClmn1Tx  ;


    @Column(name="flex_clmn2_tx", length=255)
    private String     flexClmn2Tx  ;


    @Column(name="flex_clmn3_tx", length=255)
    private String     flexClmn3Tx  ;


    @Column(name="flex_clmn4_tx", length=255)
    private String     flexClmn4Tx  ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="crte_ts")
    private Date       crteTs       ;


    @Column(name="crte_usr_id", length=255)
    private String     crteUsrId    ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updt_ts")
    private Date       updtTs       ;


    @Column(name="updt_usr_id", length=255)
    private String     updtUsrId    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public NmacUsrPrfl()
    {
		super();
    }

    public NmacUsrPrfl update(NmacUsrPrfl a) {
        this.usrKy = a.usrKy;
        this.usrId = a.usrId;
        this.usrFrstNm = a.usrFrstNm;
        this.usrLstNm = a.usrLstNm;
        this.flexClmn1Tx = a.flexClmn1Tx;
        this.flexClmn2Tx = a.flexClmn2Tx;
        this.flexClmn3Tx = a.flexClmn3Tx;
        this.flexClmn4Tx = a.flexClmn4Tx;
        this.crteTs = a.crteTs;
        this.crteUsrId = a.crteUsrId;
        this.updtTs = a.updtTs;
        this.updtUsrId = a.updtUsrId;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : usr_ky ( serial ) 
    public void setUsrKy( Integer usrKy )
    {
        this.usrKy = usrKy;
    }
    public Integer getUsrKy()
    {
        return this.usrKy;
    }

    //--- DATABASE MAPPING : usr_id ( varchar ) 
    public void setUsrId( String usrId )
    {
        this.usrId = usrId;
    }
    public String getUsrId()
    {
        return this.usrId;
    }

    //--- DATABASE MAPPING : usr_frst_nm ( varchar ) 
    public void setUsrFrstNm( String usrFrstNm )
    {
        this.usrFrstNm = usrFrstNm;
    }
    public String getUsrFrstNm()
    {
        return this.usrFrstNm;
    }

    //--- DATABASE MAPPING : usr_lst_nm ( varchar ) 
    public void setUsrLstNm( String usrLstNm )
    {
        this.usrLstNm = usrLstNm;
    }
    public String getUsrLstNm()
    {
        return this.usrLstNm;
    }

    //--- DATABASE MAPPING : flex_clmn1_tx ( varchar ) 
    public void setFlexClmn1Tx( String flexClmn1Tx )
    {
        this.flexClmn1Tx = flexClmn1Tx;
    }
    public String getFlexClmn1Tx()
    {
        return this.flexClmn1Tx;
    }

    //--- DATABASE MAPPING : flex_clmn2_tx ( varchar ) 
    public void setFlexClmn2Tx( String flexClmn2Tx )
    {
        this.flexClmn2Tx = flexClmn2Tx;
    }
    public String getFlexClmn2Tx()
    {
        return this.flexClmn2Tx;
    }

    //--- DATABASE MAPPING : flex_clmn3_tx ( varchar ) 
    public void setFlexClmn3Tx( String flexClmn3Tx )
    {
        this.flexClmn3Tx = flexClmn3Tx;
    }
    public String getFlexClmn3Tx()
    {
        return this.flexClmn3Tx;
    }

    //--- DATABASE MAPPING : flex_clmn4_tx ( varchar ) 
    public void setFlexClmn4Tx( String flexClmn4Tx )
    {
        this.flexClmn4Tx = flexClmn4Tx;
    }
    public String getFlexClmn4Tx()
    {
        return this.flexClmn4Tx;
    }

    //--- DATABASE MAPPING : crte_ts ( timestamp ) 
    public void setCrteTs( Date crteTs )
    {
        this.crteTs = crteTs;
    }
    public Date getCrteTs()
    {
        return this.crteTs;
    }

    //--- DATABASE MAPPING : crte_usr_id ( varchar ) 
    public void setCrteUsrId( String crteUsrId )
    {
        this.crteUsrId = crteUsrId;
    }
    public String getCrteUsrId()
    {
        return this.crteUsrId;
    }

    //--- DATABASE MAPPING : updt_ts ( timestamp ) 
    public void setUpdtTs( Date updtTs )
    {
        this.updtTs = updtTs;
    }
    public Date getUpdtTs()
    {
        return this.updtTs;
    }

    //--- DATABASE MAPPING : updt_usr_id ( varchar ) 
    public void setUpdtUsrId( String updtUsrId )
    {
        this.updtUsrId = updtUsrId;
    }
    public String getUpdtUsrId()
    {
        return this.updtUsrId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append("]:"); 
        sb.append(usrKy);
        sb.append("|");
        sb.append(usrId);
        sb.append("|");
        sb.append(usrFrstNm);
        sb.append("|");
        sb.append(usrLstNm);
        sb.append("|");
        sb.append(flexClmn1Tx);
        sb.append("|");
        sb.append(flexClmn2Tx);
        sb.append("|");
        sb.append(flexClmn3Tx);
        sb.append("|");
        sb.append(flexClmn4Tx);
        sb.append("|");
        sb.append(crteTs);
        sb.append("|");
        sb.append(crteUsrId);
        sb.append("|");
        sb.append(updtTs);
        sb.append("|");
        sb.append(updtUsrId);
        return sb.toString(); 
    } 

}