/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nmac.payments.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "nmac_pymnt_acnts_hs"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="nmac_pymnt_acnts_hs", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="NmacPymntAcntsHs.countAll", query="SELECT COUNT(x) FROM NmacPymntAcntsHs x" )
} )
public class NmacPymntAcntsHs implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="pymnt_acnt_hs_ky")
    private Integer    pymntAcntHsKy ;


    @Column(name="pymnt_acnt_ky", length=40)
    private String     pymntAcntKy  ;


    @Column(name="objct_nm", length=18)
    private String     objctNm      ;


    @Column(name="usr_id", length=40)
    private String     usrId        ;


    @Column(name="pymnt_typ_nm", length=10)
    private String     pymntTypNm   ;


    @Column(name="acnt_hldr_nm", length=40)
    private String     acntHldrNm   ;


    @Column(name="acnt_id", length=255)
    private String     acntId       ;


    @Column(name="acnt_typ_nm", length=40)
    private String     acntTypNm    ;


    @Column(name="acnt_usg_tx", length=40)
    private String     acntUsgTx    ;


    @Column(name="acnt_sts_tx", length=40)
    private String     acntStsTx    ;


    @Column(name="rtng_trnst_id", length=9)
    private String     rtngTrnstId  ;


    @Column(name="ntfy_src_cd", length=1)
    private String     ntfySrcCd    ;


    @Column(name="ntfy_sts_cd", length=1)
    private String     ntfyStsCd    ;


    @Column(name="trnscn_msg_tx", length=255)
    private String     trnscnMsgTx  ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trnscn_ts")
    private Date       trnscnTs     ;


    @Column(name="flex_clmn1_tx", length=255)
    private String     flexClmn1Tx  ;


    @Column(name="flex_clmn2_tx", length=255)
    private String     flexClmn2Tx  ;


    @Column(name="ntfy_exprtn_sts_cd", length=1)
    private String     ntfyExprtnStsCd ;


    @Column(name="adt_oprtn_cd")
    private BigDecimal adtOprtnCd   ;


    @Column(name="adt_sts_cd")
    private BigDecimal adtStsCd     ;


    @Column(name="adt_rsn_tx", length=2000)
    private String     adtRsnTx     ;


    @Column(name="job_ky")
    private BigDecimal jobKy        ;


    @Column(name="job_nm", length=42)
    private String     jobNm        ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="adt_ts")
    private Date       adtTs        ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="crte_ts")
    private Date       crteTs       ;


    @Column(name="crte_usr_id", length=255)
    private String     crteUsrId    ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updt_ts")
    private Date       updtTs       ;


    @Column(name="updt_usr_id", length=255)
    private String     updtUsrId    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public NmacPymntAcntsHs()
    {
		super();
    }

    public NmacPymntAcntsHs update(NmacPymntAcntsHs a) {
		this.id = a.id;
        this.pymntAcntHsKy = a.pymntAcntHsKy;
        this.pymntAcntKy = a.pymntAcntKy;
        this.objctNm = a.objctNm;
        this.usrId = a.usrId;
        this.pymntTypNm = a.pymntTypNm;
        this.acntHldrNm = a.acntHldrNm;
        this.acntId = a.acntId;
        this.acntTypNm = a.acntTypNm;
        this.acntUsgTx = a.acntUsgTx;
        this.acntStsTx = a.acntStsTx;
        this.rtngTrnstId = a.rtngTrnstId;
        this.ntfySrcCd = a.ntfySrcCd;
        this.ntfyStsCd = a.ntfyStsCd;
        this.trnscnMsgTx = a.trnscnMsgTx;
        this.trnscnTs = a.trnscnTs;
        this.flexClmn1Tx = a.flexClmn1Tx;
        this.flexClmn2Tx = a.flexClmn2Tx;
        this.ntfyExprtnStsCd = a.ntfyExprtnStsCd;
        this.adtOprtnCd = a.adtOprtnCd;
        this.adtStsCd = a.adtStsCd;
        this.adtRsnTx = a.adtRsnTx;
        this.jobKy = a.jobKy;
        this.jobNm = a.jobNm;
        this.adtTs = a.adtTs;
        this.crteTs = a.crteTs;
        this.crteUsrId = a.crteUsrId;
        this.updtTs = a.updtTs;
        this.updtUsrId = a.updtUsrId;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : pymnt_acnt_hs_ky ( serial ) 
    public void setPymntAcntHsKy( Integer pymntAcntHsKy )
    {
        this.pymntAcntHsKy = pymntAcntHsKy;
    }
    public Integer getPymntAcntHsKy()
    {
        return this.pymntAcntHsKy;
    }

    //--- DATABASE MAPPING : pymnt_acnt_ky ( varchar ) 
    public void setPymntAcntKy( String pymntAcntKy )
    {
        this.pymntAcntKy = pymntAcntKy;
    }
    public String getPymntAcntKy()
    {
        return this.pymntAcntKy;
    }

    //--- DATABASE MAPPING : objct_nm ( varchar ) 
    public void setObjctNm( String objctNm )
    {
        this.objctNm = objctNm;
    }
    public String getObjctNm()
    {
        return this.objctNm;
    }

    //--- DATABASE MAPPING : usr_id ( varchar ) 
    public void setUsrId( String usrId )
    {
        this.usrId = usrId;
    }
    public String getUsrId()
    {
        return this.usrId;
    }

    //--- DATABASE MAPPING : pymnt_typ_nm ( varchar ) 
    public void setPymntTypNm( String pymntTypNm )
    {
        this.pymntTypNm = pymntTypNm;
    }
    public String getPymntTypNm()
    {
        return this.pymntTypNm;
    }

    //--- DATABASE MAPPING : acnt_hldr_nm ( varchar ) 
    public void setAcntHldrNm( String acntHldrNm )
    {
        this.acntHldrNm = acntHldrNm;
    }
    public String getAcntHldrNm()
    {
        return this.acntHldrNm;
    }

    //--- DATABASE MAPPING : acnt_id ( varchar ) 
    public void setAcntId( String acntId )
    {
        this.acntId = acntId;
    }
    public String getAcntId()
    {
        return this.acntId;
    }

    //--- DATABASE MAPPING : acnt_typ_nm ( varchar ) 
    public void setAcntTypNm( String acntTypNm )
    {
        this.acntTypNm = acntTypNm;
    }
    public String getAcntTypNm()
    {
        return this.acntTypNm;
    }

    //--- DATABASE MAPPING : acnt_usg_tx ( varchar ) 
    public void setAcntUsgTx( String acntUsgTx )
    {
        this.acntUsgTx = acntUsgTx;
    }
    public String getAcntUsgTx()
    {
        return this.acntUsgTx;
    }

    //--- DATABASE MAPPING : acnt_sts_tx ( varchar ) 
    public void setAcntStsTx( String acntStsTx )
    {
        this.acntStsTx = acntStsTx;
    }
    public String getAcntStsTx()
    {
        return this.acntStsTx;
    }

    //--- DATABASE MAPPING : rtng_trnst_id ( varchar ) 
    public void setRtngTrnstId( String rtngTrnstId )
    {
        this.rtngTrnstId = rtngTrnstId;
    }
    public String getRtngTrnstId()
    {
        return this.rtngTrnstId;
    }

    //--- DATABASE MAPPING : ntfy_src_cd ( bpchar ) 
    public void setNtfySrcCd( String ntfySrcCd )
    {
        this.ntfySrcCd = ntfySrcCd;
    }
    public String getNtfySrcCd()
    {
        return this.ntfySrcCd;
    }

    //--- DATABASE MAPPING : ntfy_sts_cd ( bpchar ) 
    public void setNtfyStsCd( String ntfyStsCd )
    {
        this.ntfyStsCd = ntfyStsCd;
    }
    public String getNtfyStsCd()
    {
        return this.ntfyStsCd;
    }

    //--- DATABASE MAPPING : trnscn_msg_tx ( varchar ) 
    public void setTrnscnMsgTx( String trnscnMsgTx )
    {
        this.trnscnMsgTx = trnscnMsgTx;
    }
    public String getTrnscnMsgTx()
    {
        return this.trnscnMsgTx;
    }

    //--- DATABASE MAPPING : trnscn_ts ( timestamp ) 
    public void setTrnscnTs( Date trnscnTs )
    {
        this.trnscnTs = trnscnTs;
    }
    public Date getTrnscnTs()
    {
        return this.trnscnTs;
    }

    //--- DATABASE MAPPING : flex_clmn1_tx ( varchar ) 
    public void setFlexClmn1Tx( String flexClmn1Tx )
    {
        this.flexClmn1Tx = flexClmn1Tx;
    }
    public String getFlexClmn1Tx()
    {
        return this.flexClmn1Tx;
    }

    //--- DATABASE MAPPING : flex_clmn2_tx ( varchar ) 
    public void setFlexClmn2Tx( String flexClmn2Tx )
    {
        this.flexClmn2Tx = flexClmn2Tx;
    }
    public String getFlexClmn2Tx()
    {
        return this.flexClmn2Tx;
    }

    //--- DATABASE MAPPING : ntfy_exprtn_sts_cd ( bpchar ) 
    public void setNtfyExprtnStsCd( String ntfyExprtnStsCd )
    {
        this.ntfyExprtnStsCd = ntfyExprtnStsCd;
    }
    public String getNtfyExprtnStsCd()
    {
        return this.ntfyExprtnStsCd;
    }

    //--- DATABASE MAPPING : adt_oprtn_cd ( numeric ) 
    public void setAdtOprtnCd( BigDecimal adtOprtnCd )
    {
        this.adtOprtnCd = adtOprtnCd;
    }
    public BigDecimal getAdtOprtnCd()
    {
        return this.adtOprtnCd;
    }

    //--- DATABASE MAPPING : adt_sts_cd ( numeric ) 
    public void setAdtStsCd( BigDecimal adtStsCd )
    {
        this.adtStsCd = adtStsCd;
    }
    public BigDecimal getAdtStsCd()
    {
        return this.adtStsCd;
    }

    //--- DATABASE MAPPING : adt_rsn_tx ( varchar ) 
    public void setAdtRsnTx( String adtRsnTx )
    {
        this.adtRsnTx = adtRsnTx;
    }
    public String getAdtRsnTx()
    {
        return this.adtRsnTx;
    }

    //--- DATABASE MAPPING : job_ky ( numeric ) 
    public void setJobKy( BigDecimal jobKy )
    {
        this.jobKy = jobKy;
    }
    public BigDecimal getJobKy()
    {
        return this.jobKy;
    }

    //--- DATABASE MAPPING : job_nm ( varchar ) 
    public void setJobNm( String jobNm )
    {
        this.jobNm = jobNm;
    }
    public String getJobNm()
    {
        return this.jobNm;
    }

    //--- DATABASE MAPPING : adt_ts ( timestamp ) 
    public void setAdtTs( Date adtTs )
    {
        this.adtTs = adtTs;
    }
    public Date getAdtTs()
    {
        return this.adtTs;
    }

    //--- DATABASE MAPPING : crte_ts ( timestamp ) 
    public void setCrteTs( Date crteTs )
    {
        this.crteTs = crteTs;
    }
    public Date getCrteTs()
    {
        return this.crteTs;
    }

    //--- DATABASE MAPPING : crte_usr_id ( varchar ) 
    public void setCrteUsrId( String crteUsrId )
    {
        this.crteUsrId = crteUsrId;
    }
    public String getCrteUsrId()
    {
        return this.crteUsrId;
    }

    //--- DATABASE MAPPING : updt_ts ( timestamp ) 
    public void setUpdtTs( Date updtTs )
    {
        this.updtTs = updtTs;
    }
    public Date getUpdtTs()
    {
        return this.updtTs;
    }

    //--- DATABASE MAPPING : updt_usr_id ( varchar ) 
    public void setUpdtUsrId( String updtUsrId )
    {
        this.updtUsrId = updtUsrId;
    }
    public String getUpdtUsrId()
    {
        return this.updtUsrId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(pymntAcntHsKy);
        sb.append("|");
        sb.append(pymntAcntKy);
        sb.append("|");
        sb.append(objctNm);
        sb.append("|");
        sb.append(usrId);
        sb.append("|");
        sb.append(pymntTypNm);
        sb.append("|");
        sb.append(acntHldrNm);
        sb.append("|");
        sb.append(acntId);
        sb.append("|");
        sb.append(acntTypNm);
        sb.append("|");
        sb.append(acntUsgTx);
        sb.append("|");
        sb.append(acntStsTx);
        sb.append("|");
        sb.append(rtngTrnstId);
        sb.append("|");
        sb.append(ntfySrcCd);
        sb.append("|");
        sb.append(ntfyStsCd);
        sb.append("|");
        sb.append(trnscnMsgTx);
        sb.append("|");
        sb.append(trnscnTs);
        sb.append("|");
        sb.append(flexClmn1Tx);
        sb.append("|");
        sb.append(flexClmn2Tx);
        sb.append("|");
        sb.append(ntfyExprtnStsCd);
        sb.append("|");
        sb.append(adtOprtnCd);
        sb.append("|");
        sb.append(adtStsCd);
        sb.append("|");
        sb.append(adtRsnTx);
        sb.append("|");
        sb.append(jobKy);
        sb.append("|");
        sb.append(jobNm);
        sb.append("|");
        sb.append(adtTs);
        sb.append("|");
        sb.append(crteTs);
        sb.append("|");
        sb.append(crteUsrId);
        sb.append("|");
        sb.append(updtTs);
        sb.append("|");
        sb.append(updtUsrId);
        return sb.toString(); 
    } 

}