/*
 * Created on 7 Sep 2017 ( Time 17:05:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.nmac.payments.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "vehicleaccountcontactjunction__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="vehicleaccountcontactjunction__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="VehicleaccountcontactjunctionC.countAll", query="SELECT COUNT(x) FROM VehicleaccountcontactjunctionC x" )
} )
public class VehicleaccountcontactjunctionC implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Column(name="vehicle_account__c", length=18)
    private String     vehicleAccountC ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="user__c", length=18)
    private String     userC        ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Column(name="name", length=80)
    private String     name         ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="uniquekey__c", length=255)
    private String     uniquekeyC   ;


    @Column(name="account_nickname__c", length=255)
    private String     accountNicknameC ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VehicleaccountcontactjunctionC()
    {
		super();
    }

    public VehicleaccountcontactjunctionC update(VehicleaccountcontactjunctionC a) {
		this.id = a.id;
        this.isdeleted = a.isdeleted;
        this.vehicleAccountC = a.vehicleAccountC;
        this.systemmodstamp = a.systemmodstamp;
        this.userC = a.userC;
        this.hcLastop = a.hcLastop;
        this.name = a.name;
        this.sfid = a.sfid;
        this.createddate = a.createddate;
        this.uniquekeyC = a.uniquekeyC;
        this.accountNicknameC = a.accountNicknameC;
        this.hcErr = a.hcErr;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : vehicle_account__c ( varchar ) 
    public void setVehicleAccountC( String vehicleAccountC )
    {
        this.vehicleAccountC = vehicleAccountC;
    }
    public String getVehicleAccountC()
    {
        return this.vehicleAccountC;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : user__c ( varchar ) 
    public void setUserC( String userC )
    {
        this.userC = userC;
    }
    public String getUserC()
    {
        return this.userC;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : uniquekey__c ( varchar ) 
    public void setUniquekeyC( String uniquekeyC )
    {
        this.uniquekeyC = uniquekeyC;
    }
    public String getUniquekeyC()
    {
        return this.uniquekeyC;
    }

    //--- DATABASE MAPPING : account_nickname__c ( varchar ) 
    public void setAccountNicknameC( String accountNicknameC )
    {
        this.accountNicknameC = accountNicknameC;
    }
    public String getAccountNicknameC()
    {
        return this.accountNicknameC;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(isdeleted);
        sb.append("|");
        sb.append(vehicleAccountC);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(userC);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(uniquekeyC);
        sb.append("|");
        sb.append(accountNicknameC);
        sb.append("|");
        sb.append(hcErr);
        return sb.toString(); 
    } 

}