/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.nmac.payments.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import javax.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.nmac.payments.model.ResponseMessage;
import com.nmac.payments.entities.NmacPymntsHs;
import com.nmac.payments.services.NmacPymntsHsService;

@Controller
@RequestMapping(value="/api/v1/nmacpymntshs")
public class NmacPymntsHsRestController {
	
	private static Logger logger = LoggerFactory.getLogger(NmacPymntsHsRestController.class);
	
	@Autowired
	private NmacPymntsHsService nmacpymntshsService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value="", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(nmacpymntshsService.findAll());
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> getAll", e);
			responseMessage.setError(-1, "Unable to get page for NmacPymntsHs: " + e.getMessage());
		}
		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(nmacpymntshsService.findAll(page, records));
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for NmacPymntsHs: " + e.getMessage());
		}
		return responseMessage;
		
	}


//	@RequestMapping(value="/count", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getCount() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("NmacPymntsHsService -> getAll");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(nmacpymntshsService.count());
//		} catch (Exception e) {
//			logger.error("NmacPymntsHsController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all NmacPymntsHs: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

//	@RequestMapping(value="/page", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getPage(@RequestParam int page,@RequestParam int size) {
//
//		if (logger.isDebugEnabled())
//			logger.debug("NmacPymntsHsService -> getPage(" + page + "," + size + ")");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(nmacpymntshsService.getPage(page, size));
//		} catch (Exception e) {
//			logger.error("NmacPymntsHsController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all NmacPymntsHs: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}
	
//	@RequestMapping(value="/elements", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getDropDownElements() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("NmacPymntsHsService -> getDropDownElements");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(nmacpymntshsService.getDropDownValues());
//		} catch (Exception e) {
//			logger.error("NmacPymntsHsController -> getDropDownElements", e);
//			responseMessage.setError(-1, "Unable to getDropDownElements for NmacPymntsHs: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

	@RequestMapping(value="/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE}, consumes = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(nmacpymntshsService.get(id));
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> create", e);
			responseMessage.setError(-1,
					"Unable to create NmacPymntsHs: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage create(@RequestBody NmacPymntsHs element) {

		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> create:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(nmacpymntshsService.create(element));
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> create", e);
			responseMessage.setError(-1,
					"Unable to create NmacPymntsHs: " + element + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Integer id, @RequestBody NmacPymntsHs element) {
		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(nmacpymntshsService.create(element));
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit NmacPymntsHs: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Integer id) {

		if (logger.isDebugEnabled())
			logger.debug("NmacPymntsHsService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			nmacpymntshsService.delete(id);
		} catch (Exception e) {
			logger.error("NmacPymntsHsController -> delete", e);
			responseMessage.setError(-1, "Unable to delete NmacPymntsHs: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
	@ExceptionHandler(Exception.class)
	public @ResponseBody
	String handleException(Exception e, HttpServletResponse response) {
	    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	    return e.getMessage();
	}

}

