/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntAcntsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntAcntsNotFoundException(Integer id) {
		super("NmacPymntAcnts not found with id: " + id.toString());
	}

	public NmacPymntAcntsNotFoundException(String nmacpymntacnts) {
		super("NmacPymntAcnts " + nmacpymntacnts + " not found!");
	}
}
