/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntAcntsHsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntAcntsHsNotFoundException(Integer id) {
		super("NmacPymntAcntsHs not found with id: " + id.toString());
	}

	public NmacPymntAcntsHsNotFoundException(String nmacpymntacntshs) {
		super("NmacPymntAcntsHs " + nmacpymntacntshs + " not found!");
	}
}
