/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntsNotFoundException(Integer id) {
		super("NmacPymnts not found with id: " + id.toString());
	}

	public NmacPymntsNotFoundException(String nmacpymnts) {
		super("NmacPymnts " + nmacpymnts + " not found!");
	}
}
