/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class NmacUsrPrflNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacUsrPrflNotFoundException(Integer id) {
		super("NmacUsrPrfl not found with id: " + id.toString());
	}

	public NmacUsrPrflNotFoundException(String nmacusrprfl) {
		super("NmacUsrPrfl " + nmacusrprfl + " not found!");
	}
}
