/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntAcntsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntAcntsNotFoundException(Integer id) {
		super("NmacPymntAcnts not found with id: " + id.toString());
	}

	public NmacPymntAcntsNotFoundException(String nmacpymntacnts) {
		super("NmacPymntAcnts " + nmacpymntacnts + " not found!");
	}
}
