/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntAcntsHsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntAcntsHsNotFoundException(Integer id) {
		super("NmacPymntAcntsHs not found with id: " + id.toString());
	}

	public NmacPymntAcntsHsNotFoundException(String nmacpymntacntshs) {
		super("NmacPymntAcntsHs " + nmacpymntacntshs + " not found!");
	}
}
