/*
 * Created on 2017-09-05 ( Time 14:16:10 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.nmac.payments.exceptions;

public class NmacUsrPrflNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacUsrPrflNotFoundException(Integer id) {
		super("NmacUsrPrfl not found with id: " + id.toString());
	}

	public NmacUsrPrflNotFoundException(String nmacusrprfl) {
		super("NmacUsrPrfl " + nmacusrprfl + " not found!");
	}
}
