/*
 * Created on 5 Sep 2017 ( Time 14:30:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class NmacPymntsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacPymntsNotFoundException(Integer id) {
		super("NmacPymnts not found with id: " + id.toString());
	}

	public NmacPymntsNotFoundException(String nmacpymnts) {
		super("NmacPymnts " + nmacpymnts + " not found!");
	}
}
