/*
 * Created on 7 Sep 2017 ( Time 17:05:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class NmacUserNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public NmacUserNotFoundException(Integer id) {
		super("User not found with id: " + id.toString());
	}

	public NmacUserNotFoundException(String user) {
		super("User " + user + " not found!");
	}
}
