/*
 * Created on 7 Sep 2017 ( Time 17:05:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class VehicleaccountcontactjunctionCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public VehicleaccountcontactjunctionCNotFoundException(Integer id) {
		super("VehicleaccountcontactjunctionC not found with id: " + id.toString());
	}

	public VehicleaccountcontactjunctionCNotFoundException(String vehicleaccountcontactjunctionc) {
		super("VehicleaccountcontactjunctionC " + vehicleaccountcontactjunctionc + " not found!");
	}
}
