/*
 * Created on 7 Sep 2017 ( Time 17:05:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.nmac.payments.exceptions;

public class VehicleAccountCNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public VehicleAccountCNotFoundException(Integer id) {
		super("VehicleAccountC not found with id: " + id.toString());
	}

	public VehicleAccountCNotFoundException(String vehicleaccountc) {
		super("VehicleAccountC " + vehicleaccountc + " not found!");
	}
}
